### ISSUE TITLE
Does not seem to copy over files starting with a period.

### ISSUE THREAD

**Issue by donnyroufs** [streletss/bystro#1]
Template structure:

```
>  .bystro
  >  {{name}}
    >  src
    >  .eslintrc
```

seems to ignore the **.eslintrc** file.

**Comment by donnyroufs** [comment]
Looks like empty folders are also not included (which makes sense I guess?)

If you want I can pick this up during the weekend! @streletss

**Comment by streletss** [comment]
@donnyroufs sure! that would be great. been busy lately :(
after the fix you should be able to add `.gitkeep` or something to keep the folders in place
